#!/bin/bash
#
#      ___________
#     /-/_'/-/_/-/|                   B   O   R   G
#    /'-/-_'/-_//||          << https://github.com/agh/borg >>
#   /__________/|/|
#   |'|_'='-]:+|/||   Sit back and relax, human. Resistance is futile.
#   |-+-|.|_'-'||//   This should be a painless process and before long this
#   |['.[:!+-'=|//    system will be a functional part of the collective.
#   |='!+|-:]|-|/
#    ----------
#
#  Author: Alex Howells <alex@howells.me>
#  Copyright (c) 2014, Aeode Ltd <hello@aeode.com>
#  Please see the LICENSE file in the repository root for further information.
#
PATH="/opt/chefdk/bin:${PATH}"
BORG="$(cd $(dirname $0)/.. && pwd)"
BERKS_VENDOR="${BORG}/cookbooks/upstream"

function notify() {
  echo "==> $1"
}

# Banner to say we're entering the configuration management phase.
cat << __EOF__

  <><><><><><><><><><><><><><><><><><><><><><><><><><><>
                      Update Phase
  <><><><><><><><><><><><><><><><><><><><><><><><><><><>

__EOF__

chef-apply cookbooks/project/borg/recipes/update.rb

notify "😠  Reinstalling upstream cookbook dependencies with Berkshelf."

if [ -d $BERKS_VENDOR ]; then
  rm -rf $BERKS_VENDOR
fi

berks install -q
berks vendor $BERKS_VENDOR -q
